spring:
  application:
    name: online_course_platform
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:online_course_platform}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: method

app:
  admin:
    email: ${ADMIN_EMAIL:admin@gmail.com}
    password: ${ADMIN_PASSWORD:admin123}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
  jwt:
    public-key: classpath:certs/public.pem
    private-key: classpath:certs/private.pem
    expiry-seconds: 3600 # 1 hour
    refresh-expiry-seconds: 604800 # 7 days
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME:online-course-platform-bucket}
    region: ${AWS_S3_REGION:ap-southeast-1}
    presigned-expiry-minutes: ${AWS_S3_PRESIGNED_EXPIRY_MINUTES:5}
    presigned-get-expiry-minutes: ${AWS_S3_PRESIGNED_GET_EXPIRY_MINUTES:60}
    public-base-url: ${AWS_S3_PUBLIC_BASE_URL:https://online-course-platform-bucket.s3.ap-southeast-1.amazonaws.com}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID:}
    secret-key: ${AWS_SECRET_ACCESS_KEY:}
